### ISSUE TITLE
JS is not removing the hidden property

### ISSUE THREAD

**Issue by Takomane** [Takomane/takomane.github.io#8]
Wrote up the JS to remove the hidden property when the div comes into view. I think the issue might be how the CSS animation is written that the object never technically scrolls into view for JS to pick up on. 

How I want it to work is for the div5 element to be classified as hidden until it is scrolled into view. SO that when it DOES come into view, the hidden element is removed and replaced with div5 (or div5animation whichever will work, I have tried both).

**Comment by axecopfire** [comment]
Downloaded the code and saw these errors in browser
![image](https://user-images.githubusercontent.com/24581531/163679753-01c93287-aca2-4800-af68-8eb9ee9779ac.png)

**Comment by axecopfire** [comment]
You're loading `main.js` twice. Keep just one 
![image](https://user-images.githubusercontent.com/24581531/163679847-021e7043-706f-4eef-96e0-827e1ad7aba6.png)

**Comment by Takomane** [comment]
Thank you for pointing me in the right direction.
